<template><div class="page"><h2>标签体系管理</h2>
<el-button type="primary" @click="onAdd">新增类别</el-button><el-button @click="onExport" style="margin-left:8px">导出JSON</el-button><el-button @click="onImport" style="margin-left:8px">导入JSON</el-button>
<el-table :data="categories" style="margin-top:12px"><el-table-column prop="name" label="类别名称"/><el-table-column prop="shortcut" label="快捷键" width="80"/><el-table-column prop="depth_required" label="强制深度" width="80"><template #default="{row}"><el-tag :type="row.depth_required?'warning':'info'" size="small">{{row.depth_required?'是':'否'}}</el-tag></template></el-table-column><el-table-column prop="status" label="状态" width="80"><template #default="{row}"><el-tag :type="row.status==='active'?'success':'danger'" size="small">{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button size="small" @click="onDeprecate(row)" v-if="row.status==='active'">废弃</el-button></template></el-table-column></el-table>
<el-dialog v-model="addVisible" title="新增类别" width="400px"><el-form :model="newCat" label-position="top"><el-form-item label="名称"><el-input v-model="newCat.name"/></el-form-item><el-form-item label="快捷键"><el-input v-model="newCat.shortcut"/></el-form-item><el-form-item label="强制标注深度"><el-switch v-model="newCat.depth_required"/></el-form-item></el-form><template #footer><el-button @click="addVisible=false">取消</el-button><el-button type="primary" @click="onConfirmAdd">确认</el-button></template></el-dialog></div></template>
<script setup>import {ref,reactive} from 'vue';import {ElMessage} from 'element-plus'
const categories=ref([{id:1,name:'电线杆',shortcut:'w',depth_required:true,status:'active'},{id:2,name:'桥梁',shortcut:'q',depth_required:true,status:'active'},{id:3,name:'建筑物',shortcut:'e',depth_required:false,status:'active'},{id:4,name:'树木',shortcut:'r',depth_required:false,status:'active'},{id:5,name:'路灯',shortcut:'t',depth_required:false,status:'deprecated'}])
const addVisible=ref(false);const newCat=reactive({name:'',shortcut:'',depth_required:true})
function onAdd(){addVisible.value=true}
function onConfirmAdd(){categories.value.push({id:Date.now(),name:newCat.name,shortcut:newCat.shortcut,depth_required:newCat.depth_required,status:'active'});addVisible.value=false;ElMessage.success('类别已添加')}
function onDeprecate(row){row.status='deprecated';ElMessage.success('已废弃')}
function onExport(){ElMessage.success('JSON已导出（Mock）')}
function onImport(){ElMessage.success('JSON已导入（Mock）')}
</script>
<style scoped>.page{padding:24px;max-width:1000px;margin:0 auto}</style>