<template><div class="page"><h2>用户管理</h2>
<el-table :data="users"><el-table-column prop="username" label="用户名"/><el-table-column prop="email" label="邮箱"/><el-table-column prop="role" label="角色"/><el-table-column prop="is_active" label="状态"><template #default="{row}"><el-tag :type="row.is_active?'success':'danger'">{{row.is_active?'启用':'冻结'}}</el-tag></template></el-table-column><el-table-column label="操作" width="260"><template #default="{row}"><el-button size="small" @click="onPromote(row)" v-if="row.role==='normal'">提权审核员</el-button><el-button size="small" :type="row.is_active?'danger':'success'" @click="onToggle(row)">{{row.is_active?'冻结':'解冻'}}</el-button></template></el-table-column></el-table>
<el-dialog v-model="createVisible" title="创建用户" width="400px"><el-form :model="newUser" label-position="top"><el-form-item label="用户名"><el-input v-model="newUser.username"/></el-form-item><el-form-item label="密码"><el-input v-model="newUser.password" type="password"/></el-form-item><el-form-item label="邮箱"><el-input v-model="newUser.email"/></el-form-item><el-form-item label="角色"><el-select v-model="newUser.role"><el-option label="普通用户" value="normal"/><el-option label="超级账号" value="super"/></el-select></el-form-item></el-form><template #footer><el-button @click="createVisible=false">取消</el-button><el-button type="primary" @click="onCreate">创建</el-button></template></el-dialog>
<el-button type="primary" style="margin-top:16px" @click="createVisible=true">创建用户</el-button></div></template>
<script setup>import {ref,reactive} from 'vue';import {ElMessage} from 'element-plus'
const users=ref([{user_id:1,username:'admin',email:'admin@test.com',role:'admin',is_active:true},{user_id:2,username:'user1',email:'user1@test.com',role:'normal',is_active:true},{user_id:3,username:'reviewer1',email:'rev@test.com',role:'reviewer',is_active:true}])
const createVisible=ref(false);const newUser=reactive({username:'',password:'',email:'',role:'normal'})
function onPromote(row){row.role='reviewer';ElMessage.success('已提权为审核员')}
function onToggle(row){row.is_active=!row.is_active;ElMessage.success(row.is_active?'已解冻':'已冻结')}
function onCreate(){users.value.push({user_id:Date.now(),username:newUser.username,email:newUser.email,role:newUser.role,is_active:true});createVisible.value=false;ElMessage.success('用户已创建')}
</script>
<style scoped>.page{padding:24px;max-width:1200px;margin:0 auto}</style>