<template><div class="page"><h2>数据集审核</h2>
<el-table :data="items"><el-table-column prop="name" label="数据集"/><el-table-column prop="uploader" label="提交者"/><el-table-column prop="modality" label="模态"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="200"><template #default="{row}"><el-button size="small" @click="onClaim(row)" v-if="row.status==='submitted'">认领</el-button><el-button size="small" type="success" @click="onReview(row,'approved')" v-if="row.status==='reviewing'">通过</el-button><el-button size="small" type="danger" @click="onReview(row,'rejected')" v-if="row.status==='reviewing'">驳回</el-button></template></el-table-column></el-table>
<el-dialog v-model="detailVisible" title="15项检查清单" width="700px"><el-table :data="checklist"><el-table-column prop="id" label="编号" width="60"/><el-table-column prop="name" label="检查项" width="200"/><el-table-column prop="method" label="方式" width="100"/><el-table-column label="结果" width="150"><template #default="{row}"><el-radio-group v-model="row.result" size="small"><el-radio value="pass">通过</el-radio><el-radio value="na">不适用</el-radio><el-radio value="fail">存在问题</el-radio></el-radio-group></template></el-table-column></el-table><template #footer><el-button @click="detailVisible=false">取消</el-button><el-button type="primary" @click="onSubmitReview">提交审核</el-button></template></el-dialog>
</div></template>
<script setup>import {ref,reactive} from 'vue';import {ElMessage} from 'element-plus'
const items=ref([{id:1,name:'可见光城市道路 v1',uploader:'user1',modality:'可见光',status:'submitted'},{id:2,name:'红外夜间场景 v2',uploader:'user2',modality:'红外',status:'reviewing'}])
const detailVisible=ref(false);const checklist=reactive([{id:'A1',name:'文件格式合法性',method:'系统自动',result:'pass'},{id:'A2',name:'数据完整性',method:'人工判断',result:'pass'},{id:'A3',name:'图片质量',method:'人工判断',result:'pass'},{id:'A4',name:'标注状态标记准确性',method:'人工判断',result:'pass'},{id:'A5',name:'数据去重',method:'系统自动',result:'pass'},{id:'A6',name:'标签合法性',method:'系统自动',result:'pass'},{id:'A7',name:'标注框规范性',method:'系统自动',result:'pass'},{id:'A8',name:'深度值合理性',method:'系统自动',result:'pass'},{id:'A9',name:'元信息完整性',method:'系统自动',result:'pass'},{id:'A10',name:'数据集描述一致性',method:'人工判断',result:'pass'},{id:'A11',name:'命名规范',method:'系统自动',result:'pass'},{id:'A12',name:'数据脱敏',method:'人工判断',result:'pass'},{id:'A13',name:'多模态对齐检查',method:'人工判断',result:'na'},{id:'A14',name:'帧对齐/补齐合理性',method:'人工判断',result:'na'},{id:'A15',name:'标注深度来源标注',method:'人工判断',result:'pass'}])
function onClaim(row){row.status='reviewing';detailVisible.value=true;ElMessage.success('已认领')}
function onReview(row,verdict){row.status=verdict;ElMessage.success(verdict==='approved'?'已通过':'已驳回')}
function onSubmitReview(){detailVisible.value=false;items.value[1].status='approved';ElMessage.success('审核完成')}
</script>
<style scoped>.page{padding:24px;max-width:1200px;margin:0 auto}</style>